- name: Check pihole service
  command: ssh {{ ansible_user }}@{{ ansible_host }} ls -hal /etc/systemd/system/pihole.service
  delegate_to: 127.0.0.1
  register: result
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Add pihole service
  template:
    src: etc/systemd/system/pihole.service
    dest: /etc/systemd/system/pihole.service
    owner: root
    group: root
    mode: 0600
  become: yes
  when: result.rc > 0

- name: Include daemon reload if needed
  include: "tasks/daemon-reload.yaml"
  when: result.rc > 0

- name: Enable and start pihole.service
  systemd:
    name: pihole
    state: started
    enabled: yes
  become: yes
  when: result.rc > 0